
 SIGNAL void seria(unsigned int Time) { 
 
{        
twatch(Time);
  SIN='-';  //ввод  ASCII-кода  цифры

twatch(Time);
  SIN='2';  //ввод  ASCII-кода  цифры

twatch(Time);
  SIN='5';  //ввод  ASCII-кода  цифры
	
	twatch(Time);
  SIN=',';  //ввод  ASCII-кода  цифры
	
	twatch(Time);
  SIN='3';  //ввод  ASCII-кода  цифры
	
	twatch(Time);
  SIN='4';  //ввод  ASCII-кода  цифры
	
	twatch(Time);
  SIN='3';  //ввод  ASCII-кода  цифры
	
	twatch(Time);
  SIN='e';  //ввод  ASCII-кода  цифры
	
	while(1);
}

seria(1000)                
           
